config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'events#index'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :events
  resources :attendances, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User", foreign_key: "attendee_id"
  belongs_to :attended, class_name: "Event", foreign_key: "attended_id"
  
  validates :attendee_id, presence: true
  validates :attended_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :attendances, class_name: "Attendance", foreign_key: "attended_id"
  has_many :attendees, through: :attendances, dependent: :destroy

  validates :title, presence: true, length: {maximum: 50}
  validates :description, length: {maximum: 140}
  validates :event_date, presence: true

  default_scope-> {order(created_at: :desc)}
  scope :upcoming, -> { where('event_date >= ?', Time.now) }
  scope :past, -> { where('event_date < ?', Time.now) }

  # def self.upcoming_events
  #   Event.where('event_date >= ?', Date.today)
  # end

  # def self.prev_events
  #   Event.where('event_date < ?', Date.today)
  # end
  
end

app/models/user.rb
class User < ApplicationRecord

  has_many :events, class_name: "Event", foreign_key: "user_id", dependent: :destroy
  has_many :attendances, class_name: "Attendance", foreign_key: "attendee_id"
  has_many :attended_events, through: :attendances, source: :attended, dependent: :destroy

  attr_accessor :remember_token
	before_save { email.downcase! }

	validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX },
										 uniqueness: { case_sensitive: false }
										 
	has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # def attend(event)
  #   attendances.create(attended_id: event.id)
  # end

  # def not_attend(event)
  #   attended_events.delete(event)
  # end

  def attended?(uevent)
    attended_events.include?(uevent)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    #confirms a logged-in user
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :logged_in_user

  def create
    @event = Event.find(params[:attended_id])
    current_user.attendances.create(attended_id: @event.id)
    respond_to do |format|
      format.html { redirect_to @event }
      format.js {render inline: "location.reload();" }
    end
  end

  def destroy
    @event = Attendance.find(params[:id]).attended
    current_user.attended_events.delete(@event)
    respond_to do |format|
      format.html { redirect_to @event }
      format.js {render inline: "location.reload();" }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :logged_in_user, only: [ :new, :create, :destroy]

	def index
		@events = Event.all
		@upcoming_events = @events.upcoming
		@past_events = @events.past
	end

	def show
		@event = Event.find(params[:id])
	end

	def new
		@event = Event.new
	end

	def create
		@event = current_user.events.build(event_params)
		if @event.save
			@event.attendees << current_user
			flash[:success] = "Event created!"
			redirect_to current_user 
		else
			flash[:danger] = "event not created"
			render 'new'
		end
	end	

	def edit
    @event = Event.find(params[:id]) 
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event details updated"
      redirect_to @event
      # Handle a successful update.
    else
      render 'edit'
    end
  end

	def destroy
		#@event.destroy
		Event.find(params[:id]).destroy
		flash[:success] = "Event deleted"
		redirect_to root_url
	end

	private

		def event_params
			params.require(:event).permit(:title, :description, :event_date, :user_id)
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' 
      render 'new'
    end 
  end

  def destroy
    log_out if logged_in? 
    redirect_to signup_path #root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @events = @user.events
    @upcoming_events = @events.where('event_date >= ?', Time.now)
    @prev_events = @events.where('event_date < ?', Time.now)
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	 # Returns the full title on a per-page basis.
	 def full_title(page_title = '')
    base_title = "Private Events"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

   # Forgets a persistent session.
   def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
	
end

app/views/attendances/create.js.erb
$("#attend_form").html("<%= escape_javascript(render('events/will_not_attend')) %>");
$("#attendees").html('<%= @event.attendees.count %>');

app/views/attendances/destroy.js.erb
$("#attend_form").html("<%= escape_javascript(render('events/will_attend')) %>");
$("#attendees").html('<%= @event.attendees.count %>');

app/views/events/_attend_form.html.erb
<% if @event.event_date > Time.now %>
  <div id="follow_form">
    <% if current_user.attended?(@event) %>
      <%= render 'will_not_attend' %>
    <% else %>  
      <%= render 'will_attend' %>
    <% end %>
  </div>
<% else %>
  You cannot attend this event  
<% end %>

 

app/views/events/_event.html.erb
<li id="event-<%= @event.id %>">
  <span class="user">
  	<h3><%= event.title %></h3>
  </span>
	<span class="content">
		Date: <%= event.event_date.strftime("%d-%m-%Y %I:%M %p") %><br>
		<p><%= event.description %></p>
		Event by: <%= link_to event.creator.name, event.creator %>
	</span>
  <span class="timestamp">
		Posted <%= time_ago_in_words(event.created_at) %> ago.
		<% if current_user?(event.creator) %>
			<% if event.event_date >= Time.now %> 
				<%= link_to "delete", event, method: :delete,
																				data: { confirm: "You sure?" } %>
			<% end %>																	 
    <% end %>
  </span>
</li>

app/views/events/_will_attend.html.erb
<%= form_for(current_user.attendances.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :attended_id, @event.id %></div>
  <%= f.submit "Will attend", class: "btn btn-primary" %>
<% end %>

app/views/events/_will_not_attend.html.erb
<%= form_for(current_user.attendances.find_by(attended_id: @event.id), 
            html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Will not attend", class: "btn" %>            
<% end %>

app/views/events/edit.html.erb
<% provide(:title, 'Update Event') %>
<h1>Update Event</h1>

<script>
  $( function() {
    $( "#date" ).datetimepicker({  
         minDate:new Date()
      });
  } );
</script>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>

        <%= f.label :date %>
        <%= f.text_field :event_date, class: 'form-control', id: 'date', 
                                  data: { date_format: 'YYYY/MM/DD hh:mm A'} %>
      </div>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
</div>
</div>

app/views/events/index.html.erb
<% provide(:title, 'All events') %>
<h1>All events</h1>

<ul class="users">
  <h2>Upcoming events</h2>
  <% if @upcoming_events.any? %>
    <% @upcoming_events.each do |uevents| %>
      <%= link_to uevents.title, uevents%><br>  
    <% end %>
  <% else %>
      No upcoming events
  <% end %>
  <h2>Previous events</h2>
  <%if @past_events.any? %>
    <% @past_events.each do |pevents| %>
      <%= link_to pevents.title, pevents %><br>
    <% end %>
  <% else %>  
    No previous events
  <% end %>
</ul>

app/views/events/new.html.erb
<% provide(:title, 'Create Event') %>
<h1>Create Event</h1>

<script>
  $( function() {
    $( "#date" ).datetimepicker({  
         minDate:new Date()
      });
  } );
</script>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>

        <%= f.label :date %>
        <%= f.text_field :event_date, class: 'form-control', id: 'date', 
                                  data: { date_format: 'YYYY/MM/DD hh:mm A'} %>
      </div>
      <%= f.submit "Create Event", class: "btn btn-primary" %>
    <% end %>
</div>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render @event %>
      <% if current_user?(@event.creator) %>
        <%= link_to "Edit Event", edit_event_path %>
      <% end %>  
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'attend_form' if logged_in? %>
    <ul>
      <% if @event.attendees.any? %>
        <h4>  <%= @event.attendees.count %> will attend </h4>
        <h3>Attendees: </h3>
        <% @event.attendees.each do |attendee|%>
          <%= link_to attendee.name, attendee%><br>
        <% end %>
      <% else %>
        No Attendees
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Private Events", root_path, id: "logo" %>
    <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Events", events_path %></li>      
      <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Create Event", new_event_url %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up",   signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %> 
    </ul>
    </nav>
  </div>
</header>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>  
<div class="users">
  <h2>Attended events</h2>
  <% if @user.attended_events.any? %>
    <h4> <%= pluralize(@user.attended_events.count, "event") %> attended </h4>
    <% @user.attended_events.each do |attended| %>
      <%= link_to attended.title, attended%><br>
    <% end %>
  <% else %>
    attended no events
  <% end %>
</div>
<div class="users">
  <h2>Upcoming events</h2>
  <% if @upcoming_events.any? %>
    <% @upcoming_events.each do |uevents| %>
      <%= link_to uevents.title, uevents %><br>
    <% end %>
  <% end %>
</div>
<div class="users">
  <h2>Previous events</h2>
  <% if @prev_events.any? %>
    <% @prev_events.each do |pevents| %>
      <%= link_to pevents.title, pevents %><br>
    <% end %>
  <% end %>
</div>